version: '3'
services:
  api:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
  db:
    image: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_db
    restart: always
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge